package policine;
import java.util.Random;
import javax.swing.JOptionPane;
/**
 *
 * @author Usuario
 */
public class GUI_Sala extends javax.swing.JFrame {

    public static String tipoSala = "";
    public static double precioTotal ;
    public static int numeroEntradas = 0;
    public static int opcion;
    /**
     * Creates new form GUI_Sala
     */
    public GUI_Sala() {
        initComponents();
        setLocationRelativeTo(null);
        generarHora();
        setTitle("Sala");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgTipoSala = new javax.swing.ButtonGroup();
        btgHorarios = new javax.swing.ButtonGroup();
        jblTipoSala = new javax.swing.JLabel();
        jblIngresoTickets = new javax.swing.JLabel();
        jblHorarios = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNumTickets = new javax.swing.JTextPane();
        btnRetroceder = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        rbtSala2D = new javax.swing.JRadioButton();
        rbtSala3D = new javax.swing.JRadioButton();
        rbtHora1 = new javax.swing.JRadioButton();
        rbtHora2 = new javax.swing.JRadioButton();
        rbtHora3 = new javax.swing.JRadioButton();
        rbtHora4 = new javax.swing.JRadioButton();
        jblPoliSala = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblTipoSala.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jblTipoSala.setText("Tipo de Sala:");
        getContentPane().add(jblTipoSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jblIngresoTickets.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jblIngresoTickets.setText("Ingrese los números de tickets:");
        getContentPane().add(jblIngresoTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jblHorarios.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jblHorarios.setText("Horarios:");
        getContentPane().add(jblHorarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        txtNumTickets.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumTicketsKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtNumTickets);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 60, 30));

        btnRetroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        btnRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 50, 30));

        btnGuardar.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 90, 30));

        btgTipoSala.add(rbtSala2D);
        rbtSala2D.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        rbtSala2D.setText("Sala 2D");
        getContentPane().add(rbtSala2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        btgTipoSala.add(rbtSala3D);
        rbtSala3D.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        rbtSala3D.setText("Sala 3D");
        getContentPane().add(rbtSala3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        btgHorarios.add(rbtHora1);
        rbtHora1.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        getContentPane().add(rbtHora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        btgHorarios.add(rbtHora2);
        rbtHora2.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        getContentPane().add(rbtHora2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        btgHorarios.add(rbtHora3);
        rbtHora3.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        rbtHora3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(rbtHora3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        btgHorarios.add(rbtHora4);
        rbtHora4.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        rbtHora4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(rbtHora4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, -1));

        jblPoliSala.setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N
        jblPoliSala.setText("Poli Sala");
        getContentPane().add(jblPoliSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sala.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    public void generarHora(){
        
        int digito1 = (int)(Math.random()*10);
        int digito2 = (int)(Math.random()*10);
        int digito3 = (int)(Math.random()*5);
        int digito4 = (int)(Math.random()*5);
        
        String hora1 = digito1+digito3+":"+digito3+digito4+" pm";
        String hora2 = digito1+digito4+":"+digito4+digito3+" pm";
        String hora3 = digito2+digito3+":"+digito4+digito4+" pm";
        String hora4 = digito2+digito4+":"+digito3+digito3+" pm";
        
        rbtHora1.setText(String.valueOf(hora1));
        rbtHora2.setText(String.valueOf(hora2));
        rbtHora3.setText(String.valueOf(hora3));
        rbtHora4.setText(String.valueOf(hora4));
    }
    public boolean habilitarBotones(){
        if(!txtNumTickets.getText().isEmpty()){
            return true;
        }else{
            return false;
        }
    }
    private void btnRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederActionPerformed
        // TODO add your handling code here:
        GUI_Main v1 = new GUI_Main();
        v1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRetrocederActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if(habilitarBotones() == false){
            JOptionPane.showMessageDialog(null, "Debe inrgesar todos los campos");
        }else{
            GUI_Main m1 = new GUI_Main();
            m1.setVisible(true);
            m1.jtbTienda.setEnabledAt(0, false);
            m1.jtbTienda.setEnabledAt(1, true);
            m1.cmbGenero.setEnabled(false);
            this.setVisible(false);
            if (rbtSala2D.isSelected()) {
                tipoSala = "Sala 2D";
                numeroEntradas = Integer.parseInt(txtNumTickets.getText());
                precioTotal = numeroEntradas * 4.50;

            } else {
                tipoSala = "Sala 3D";
                numeroEntradas = Integer.parseInt(txtNumTickets.getText());
                precioTotal = numeroEntradas * 4.50;
            }
            Sala s1 = new Sala(tipoSala, numeroEntradas, precioTotal);

        }
            
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNumTicketsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumTicketsKeyTyped
        // TODO add your handling code here:
                char validacion1 = evt.getKeyChar();
        if (Character.isLetter(validacion1)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo se permiten Numeros");
        }
    }//GEN-LAST:event_txtNumTicketsKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Sala().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgHorarios;
    private javax.swing.ButtonGroup btgTipoSala;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRetroceder;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jblHorarios;
    private javax.swing.JLabel jblIngresoTickets;
    private javax.swing.JLabel jblPoliSala;
    private javax.swing.JLabel jblTipoSala;
    private javax.swing.JRadioButton rbtHora1;
    private javax.swing.JRadioButton rbtHora2;
    private javax.swing.JRadioButton rbtHora3;
    private javax.swing.JRadioButton rbtHora4;
    private javax.swing.JRadioButton rbtSala2D;
    private javax.swing.JRadioButton rbtSala3D;
    private javax.swing.JTextPane txtNumTickets;
    // End of variables declaration//GEN-END:variables
}
