package policine;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class GUI_Usuario extends javax.swing.JFrame {

    public static String nombre="";
    public static String apellido="";
    public static String cedula="";
    
    /**
     * Creates new form GUI_Usuario
     */
    public GUI_Usuario() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Usuario");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnGenerarFactura = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jblNombre = new javax.swing.JLabel();
        jblApellido = new javax.swing.JLabel();
        jblCedula = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        jblDatosPersonales = new javax.swing.JLabel();
        jblCedulaUsuario = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGenerarFactura.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnGenerarFactura.setText("Generar Factura");
        btnGenerarFactura.setEnabled(false);
        btnGenerarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarFacturaActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        jblNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jblNombre.setText("Nombre");
        getContentPane().add(jblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jblApellido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jblApellido.setText("Apellido");
        getContentPane().add(jblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jblCedula.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jblCedula.setText("Cedula");
        getContentPane().add(jblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 111, -1));

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 111, -1));

        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });
        getContentPane().add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 111, -1));

        jblDatosPersonales.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jblDatosPersonales.setText("Datos Personales");
        getContentPane().add(jblDatosPersonales, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jblCedulaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.jpg"))); // NOI18N
        getContentPane().add(jblCedulaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void habilitarBotones() {//sobanepes steeven
        if (!txtNombre.getText().isEmpty() && !txtApellido.getText().isEmpty() && !txtCedula.getText().isEmpty()) {
            btnGuardar.setEnabled(true);
        }
    }
    private void btnGenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarFacturaActionPerformed
        // TODO add your handling code here:
        GUI_Factura f1 = new GUI_Factura();
        JOptionPane.showMessageDialog(null, "Datos Guardados Correctamente!!!");
        f1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGenerarFacturaActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        char validacion1 = evt.getKeyChar();
        if (Character.isDigit(validacion1)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo se permiten Letras");
        }
        habilitarBotones();
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        // TODO add your handling code here:
        char validacion1=evt.getKeyChar();
        if(Character.isDigit(validacion1)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo se permiten Letras");
        }
        habilitarBotones();
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        // TODO add your handling code here:
        char validacion1=evt.getKeyChar();
        if(Character.isLetter(validacion1)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo se permiten Numeros");
        }
        if(txtCedula.getText().length()>=10){
                evt.consume();
                getToolkit().beep();
        }
        habilitarBotones();
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        Cedula miCedula = new Cedula();
        nombre=txtNombre.getText();
        apellido = txtApellido.getText();
        cedula = txtCedula.getText();
        Usuario miUsuario = new Usuario(nombre, apellido, cedula);
        
        if (miCedula.esValida(txtCedula.getText())) {
            btnGenerarFactura.setEnabled(true);

        } else {
            JOptionPane.showMessageDialog(null, "Cedula Incorrecta!!!");
            txtCedula.requestFocus();
        }
        
    
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarFactura;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jblApellido;
    private javax.swing.JLabel jblCedula;
    private javax.swing.JLabel jblCedulaUsuario;
    private javax.swing.JLabel jblDatosPersonales;
    private javax.swing.JLabel jblNombre;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtCedula;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
