package policine;

import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author E2
 */
public class GUI_Main extends javax.swing.JFrame {

    int contador=1;
    
    /**
     * Creates new form GUI_Main
     */
    
    String accion[] = {"/imagenes/p1.jpg", "/imagenes/p2.jpg", "/imagenes/p3.jpg", "/imagenes/p4.jpg", "/imagenes/p5.jpg", "/imagenes/p6.jpg","/imagenes/p7.jpg","/imagenes/p8.jpg"};
    String drama[] = {"/imagenes/d1.jpg", "/imagenes/d2.jpg", "/imagenes/d3.jpg", "/imagenes/d4.jpg", "/imagenes/d5.jpg", "/imagenes/d6.jpg","/imagenes/d7.jpg","/imagenes/d8.jpg"};
    String terror[] = {"/imagenes/t1.jpg", "/imagenes/t2.jpg", "/imagenes/t3.jpg", "/imagenes/t4.jpg", "/imagenes/t5.jpg", "/imagenes/t6.jpg","/imagenes/t7.jpg","/imagenes/t8.jpg"};
    String suspenso[] = {"/imagenes/s1.jpg", "/imagenes/s2.jpg", "/imagenes/s3.jpg", "/imagenes/s4.jpg", "/imagenes/s5.jpg", "/imagenes/s6.jpg","/imagenes/s7.jpg","/imagenes/s8.jpg"};
    String aventura[] = {"/imagenes/a1.jpg", "/imagenes/a2.jpg", "/imagenes/a3.jpg", "/imagenes/a4.jpg", "/imagenes/a5.jpg", "/imagenes/a6.jpg","/imagenes/a7.jpg","/imagenes/a8.jpg"};
    String ciencia[] = {"/imagenes/c1.jpg", "/imagenes/c2.jpg", "/imagenes/c3.jpg", "/imagenes/c4.jpg", "/imagenes/c5.jpg", "/imagenes/c6.jpg","/imagenes/c7.jpg","/imagenes/c8.jpg"};
    String musical[] = {"/imagenes/m1.jpeg", "/imagenes/m2.jpg", "/imagenes/m3.jpg", "/imagenes/m4.jpg", "/imagenes/m5.jpg", "/imagenes/m6.jpg","/imagenes/m7.jpg","/imagenes/m8.jpg"};
    String infantil[] = {"/imagenes/i1.jpg", "/imagenes/i2.png", "/imagenes/i3.jpg", "/imagenes/i4.jpg", "/imagenes/i5.jpg", "/imagenes/i6.jpg","/imagenes/i7.jpg","/imagenes/i8.jpg"};

    public GUI_Main() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public int aumentar(){
        return contador++;
    }
    
    public int disminuir(){
        
        if (contador<=0){
            return contador=0;
        }
        return contador--;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jblV2 = new javax.swing.JLabel();
        jblV3 = new javax.swing.JLabel();
        jblV5 = new javax.swing.JLabel();
        jblV1 = new javax.swing.JLabel();
        jblV6 = new javax.swing.JLabel();
        jblV7 = new javax.swing.JLabel();
        jblV4 = new javax.swing.JLabel();
        jblV8 = new javax.swing.JLabel();
        jblHotDog = new javax.swing.JPanel();
        PoliSnacks = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jblPapas = new javax.swing.JLabel();
        jblCanguil = new javax.swing.JLabel();
        jblNachos = new javax.swing.JLabel();
        jblHotDoh = new javax.swing.JLabel();
        jblKFC = new javax.swing.JLabel();
        jblBebidas = new javax.swing.JLabel();
        jblDulces = new javax.swing.JLabel();
        jblPoliburguer = new javax.swing.JLabel();
        btnDisminuirCanguil = new javax.swing.JButton();
        btnDisminuirNachos = new javax.swing.JButton();
        btnDisminuirPapas = new javax.swing.JButton();
        btnDisminuirHotDog = new javax.swing.JButton();
        btnDisminuirKFC = new javax.swing.JButton();
        btnDisminuirBebida = new javax.swing.JButton();
        btnDisminuirDulces = new javax.swing.JButton();
        btnDisminuirBurguer = new javax.swing.JButton();
        btnAumentarCanguil = new javax.swing.JButton();
        btnAumentarNachos = new javax.swing.JButton();
        btnAumentarPapas = new javax.swing.JButton();
        btnAumentarHot = new javax.swing.JButton();
        btnAumentarKFC = new javax.swing.JButton();
        btnAumentarBebida = new javax.swing.JButton();
        btnAumentarDulce = new javax.swing.JButton();
        btnAumentarBurguer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Genero:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 31, 80, 27));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acción", "Drama", "Terror", "Suspenso", "Aventura", "Ciencia Ficción", "Musical", "Infantil" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 37, 229, -1));

        jblV2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/c1.jpg"))); // NOI18N
        jPanel1.add(jblV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, 143));

        jblV3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/d1.jpg"))); // NOI18N
        jPanel1.add(jblV3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 105, 143));

        jblV5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/p1.jpg"))); // NOI18N
        jPanel1.add(jblV5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 150));

        jblV1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a1.jpg"))); // NOI18N
        jPanel1.add(jblV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 143));

        jblV6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/s1.jpg"))); // NOI18N
        jPanel1.add(jblV6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, 150));

        jblV7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/t1.jpg"))); // NOI18N
        jPanel1.add(jblV7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 100, 150));

        jblV4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/i1.jpg"))); // NOI18N
        jPanel1.add(jblV4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 100, 140));

        jblV8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/m2.jpg"))); // NOI18N
        jPanel1.add(jblV8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 100, 150));

        jTabbedPane1.addTab("Inicio", jPanel1);

        PoliSnacks.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PoliSnacks.setText("PoliSnacks");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/poliburguer.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/polihotdog.jpg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/polinachos.jpg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/polipapas.jpg"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel6.setText("PoliCanguil");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel7.setText("PoliNachos");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel8.setText("PoliPapas");

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel9.setText("PoliHotdog");

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel10.setText("$3.35");

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel11.setText("$4.00");

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel12.setText("$2.50");

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel13.setText("$4.00");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/policanguil.jpg"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/policola.jpg"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/polichocolate.jpg"))); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/polikfc.jpg"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel18.setText("PoliKFC");

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel19.setText("PoliBebidas");

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel20.setText("PoliDulces");

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel21.setText("Poliburguer");

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel22.setText("$5.00");

        jLabel23.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel23.setText("$3.00");

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel24.setText("$2.00");

        jLabel25.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel25.setText("$4.50");

        jblPapas.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jblPapas.setForeground(new java.awt.Color(0, 153, 255));
        jblPapas.setText("0");

        jblCanguil.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jblCanguil.setForeground(new java.awt.Color(0, 153, 255));
        jblCanguil.setText("0");

        jblNachos.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jblNachos.setForeground(new java.awt.Color(0, 153, 255));
        jblNachos.setText("0");

        jblHotDoh.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jblHotDoh.setForeground(new java.awt.Color(0, 153, 255));
        jblHotDoh.setText("0");

        jblKFC.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jblKFC.setForeground(new java.awt.Color(0, 153, 255));
        jblKFC.setText("0");

        jblBebidas.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jblBebidas.setForeground(new java.awt.Color(0, 153, 255));
        jblBebidas.setText("0");

        jblDulces.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jblDulces.setForeground(new java.awt.Color(0, 153, 255));
        jblDulces.setText("0");

        jblPoliburguer.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jblPoliburguer.setForeground(new java.awt.Color(0, 153, 255));
        jblPoliburguer.setText("0");

        btnDisminuirCanguil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disminuir.png"))); // NOI18N
        btnDisminuirCanguil.setBorderPainted(false);
        btnDisminuirCanguil.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDisminuirCanguil.setDisabledSelectedIcon(null);
        btnDisminuirCanguil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisminuirCanguilActionPerformed(evt);
            }
        });

        btnDisminuirNachos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disminuir.png"))); // NOI18N
        btnDisminuirNachos.setBorderPainted(false);
        btnDisminuirNachos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDisminuirNachos.setDisabledSelectedIcon(null);
        btnDisminuirNachos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisminuirNachosActionPerformed(evt);
            }
        });

        btnDisminuirPapas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disminuir.png"))); // NOI18N
        btnDisminuirPapas.setBorderPainted(false);
        btnDisminuirPapas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDisminuirPapas.setDisabledSelectedIcon(null);
        btnDisminuirPapas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisminuirPapasActionPerformed(evt);
            }
        });

        btnDisminuirHotDog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disminuir.png"))); // NOI18N
        btnDisminuirHotDog.setBorderPainted(false);
        btnDisminuirHotDog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDisminuirHotDog.setDisabledSelectedIcon(null);
        btnDisminuirHotDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisminuirHotDogActionPerformed(evt);
            }
        });

        btnDisminuirKFC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disminuir.png"))); // NOI18N
        btnDisminuirKFC.setBorderPainted(false);
        btnDisminuirKFC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDisminuirKFC.setDisabledSelectedIcon(null);
        btnDisminuirKFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisminuirKFCActionPerformed(evt);
            }
        });

        btnDisminuirBebida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disminuir.png"))); // NOI18N
        btnDisminuirBebida.setBorderPainted(false);
        btnDisminuirBebida.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDisminuirBebida.setDisabledSelectedIcon(null);
        btnDisminuirBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisminuirBebidaActionPerformed(evt);
            }
        });

        btnDisminuirDulces.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disminuir.png"))); // NOI18N
        btnDisminuirDulces.setBorderPainted(false);
        btnDisminuirDulces.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDisminuirDulces.setDisabledSelectedIcon(null);
        btnDisminuirDulces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisminuirDulcesActionPerformed(evt);
            }
        });

        btnDisminuirBurguer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disminuir.png"))); // NOI18N
        btnDisminuirBurguer.setBorderPainted(false);
        btnDisminuirBurguer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDisminuirBurguer.setDisabledSelectedIcon(null);
        btnDisminuirBurguer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisminuirBurguerActionPerformed(evt);
            }
        });

        btnAumentarCanguil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir.png"))); // NOI18N
        btnAumentarCanguil.setBorderPainted(false);
        btnAumentarCanguil.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAumentarCanguil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarCanguilActionPerformed(evt);
            }
        });

        btnAumentarNachos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir.png"))); // NOI18N
        btnAumentarNachos.setBorderPainted(false);
        btnAumentarNachos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAumentarNachos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarNachosActionPerformed(evt);
            }
        });

        btnAumentarPapas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir.png"))); // NOI18N
        btnAumentarPapas.setBorderPainted(false);
        btnAumentarPapas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAumentarPapas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarPapasActionPerformed(evt);
            }
        });

        btnAumentarHot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir.png"))); // NOI18N
        btnAumentarHot.setBorderPainted(false);
        btnAumentarHot.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAumentarHot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarHotActionPerformed(evt);
            }
        });

        btnAumentarKFC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir.png"))); // NOI18N
        btnAumentarKFC.setBorderPainted(false);
        btnAumentarKFC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAumentarKFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarKFCActionPerformed(evt);
            }
        });

        btnAumentarBebida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir.png"))); // NOI18N
        btnAumentarBebida.setBorderPainted(false);
        btnAumentarBebida.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAumentarBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarBebidaActionPerformed(evt);
            }
        });

        btnAumentarDulce.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir.png"))); // NOI18N
        btnAumentarDulce.setBorderPainted(false);
        btnAumentarDulce.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAumentarDulce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarDulceActionPerformed(evt);
            }
        });

        btnAumentarBurguer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir.png"))); // NOI18N
        btnAumentarBurguer.setBorderPainted(false);
        btnAumentarBurguer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAumentarBurguer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarBurguerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jblHotDogLayout = new javax.swing.GroupLayout(jblHotDog);
        jblHotDog.setLayout(jblHotDogLayout);
        jblHotDogLayout.setHorizontalGroup(
            jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jblHotDogLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(PoliSnacks)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jblHotDogLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel18)
                .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jblHotDogLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel19))
                    .addGroup(jblHotDogLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnDisminuirBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jblBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jblHotDogLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(btnDisminuirDulces, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25)
                            .addGroup(jblHotDogLayout.createSequentialGroup()
                                .addComponent(btnDisminuirBurguer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jblPoliburguer, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAumentarBurguer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jblHotDogLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel20)
                        .addGap(78, 78, 78)
                        .addComponent(jLabel21)))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jblHotDogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jblHotDogLayout.createSequentialGroup()
                        .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jblHotDogLayout.createSequentialGroup()
                                .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22)
                                    .addGroup(jblHotDogLayout.createSequentialGroup()
                                        .addComponent(btnDisminuirKFC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jblKFC, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAumentarKFC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jblHotDogLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jblHotDogLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(62, 62, 62))
                    .addGroup(jblHotDogLayout.createSequentialGroup()
                        .addComponent(btnDisminuirCanguil, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jblCanguil, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAumentarCanguil, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jblHotDogLayout.createSequentialGroup()
                        .addComponent(btnDisminuirNachos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jblNachos, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAumentarNachos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jblPapas, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jblHotDogLayout.createSequentialGroup()
                        .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jblHotDogLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jblHotDogLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel11))
                                    .addComponent(jLabel7)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jblHotDogLayout.createSequentialGroup()
                                .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAumentarBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jblHotDogLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(40, 40, 40)))
                        .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jblHotDogLayout.createSequentialGroup()
                                .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDisminuirPapas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48))
                            .addGroup(jblHotDogLayout.createSequentialGroup()
                                .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAumentarPapas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jblHotDogLayout.createSequentialGroup()
                                            .addGap(40, 40, 40)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jblHotDogLayout.createSequentialGroup()
                                            .addGap(64, 64, 64)
                                            .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jblHotDogLayout.createSequentialGroup()
                                                    .addGap(10, 10, 10)
                                                    .addComponent(jLabel12))
                                                .addComponent(jLabel8))))
                                    .addGroup(jblHotDogLayout.createSequentialGroup()
                                        .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel24)
                                            .addComponent(jblDulces, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnAumentarDulce, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(51, 51, 51)))
                        .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jblHotDogLayout.createSequentialGroup()
                                    .addComponent(btnDisminuirHotDog, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jblHotDoh)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAumentarHot, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jblHotDogLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel13)))
                        .addGap(28, 28, 28))))
        );
        jblHotDogLayout.setVerticalGroup(
            jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jblHotDogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PoliSnacks)
                .addGap(6, 6, 6)
                .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jblHotDogLayout.createSequentialGroup()
                        .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jblHotDogLayout.createSequentialGroup()
                                .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)))
                            .addGroup(jblHotDogLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13))
                            .addComponent(jLabel11)))
                    .addGroup(jblHotDogLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDisminuirCanguil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jblNachos)
                        .addComponent(jblPapas)
                        .addComponent(jblCanguil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDisminuirNachos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDisminuirPapas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAumentarCanguil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAumentarNachos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAumentarPapas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jblHotDoh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDisminuirHotDog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAumentarHot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jblHotDogLayout.createSequentialGroup()
                        .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jblHotDogLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jblKFC))
                            .addGroup(jblHotDogLayout.createSequentialGroup()
                                .addComponent(jblBebidas)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btnDisminuirKFC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDisminuirBebida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAumentarKFC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAumentarBebida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jblHotDogLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAumentarBurguer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jblHotDogLayout.createSequentialGroup()
                                .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jblPoliburguer)
                                    .addComponent(btnDisminuirBurguer))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jblHotDogLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jblHotDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jblDulces, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDisminuirDulces, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAumentarDulce, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(16, 16, 16))
        );

        jTabbedPane1.addTab("Tienda", jblHotDog);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        String genero = (String) jComboBox1.getSelectedItem();
        switch (genero) {
            case "Acción":
                try {
                        URL url = this.getClass().getResource(accion[0]);
                        Image img1 = ImageIO.read(url);
                        jblV1.setIcon(new ImageIcon(img1));
                        url = this.getClass().getResource(accion[1]);
                        Image img2 = ImageIO.read(url);
                        jblV2.setIcon(new ImageIcon(img2));
                        url = this.getClass().getResource(accion[2]);
                        Image img3 = ImageIO.read(url);
                        jblV3.setIcon(new ImageIcon(img3));
                        url = this.getClass().getResource(accion[3]);
                        Image img4 = ImageIO.read(url);
                        jblV4.setIcon(new ImageIcon(img4));
                        url = this.getClass().getResource(accion[4]);
                        Image img5 = ImageIO.read(url);
                        jblV5.setIcon(new ImageIcon(img5));
                        url = this.getClass().getResource(accion[5]);
                        Image img6 = ImageIO.read(url);                                
                        jblV6.setIcon(new ImageIcon(img6));
                        url = this.getClass().getResource(accion[6]);
                        Image img7 = ImageIO.read(url);                                
                        jblV7.setIcon(new ImageIcon(img7));
                        url = this.getClass().getResource(accion[7]);
                        Image img8 = ImageIO.read(url);                                
                        jblV8.setIcon(new ImageIcon(img8));
                    } catch (Exception e) {
                    }
                break;
            case "Drama": 
                try {
                        URL url = this.getClass().getResource(drama[0]);
                        Image img1 = ImageIO.read(url);
                        jblV1.setIcon(new ImageIcon(img1));
                        url = this.getClass().getResource(drama[1]);
                        Image img2 = ImageIO.read(url);
                        jblV2.setIcon(new ImageIcon(img2));
                        url = this.getClass().getResource(drama[2]);
                        Image img3 = ImageIO.read(url);
                        jblV3.setIcon(new ImageIcon(img3));
                        url = this.getClass().getResource(drama[3]);
                        Image img4 = ImageIO.read(url);
                        jblV4.setIcon(new ImageIcon(img4));
                        url = this.getClass().getResource(drama[4]);
                        Image img5 = ImageIO.read(url);
                        jblV5.setIcon(new ImageIcon(img5));
                        url = this.getClass().getResource(drama[5]);
                        Image img6 = ImageIO.read(url);                                
                        jblV6.setIcon(new ImageIcon(img6));
                        url = this.getClass().getResource(drama[6]);
                        Image img7 = ImageIO.read(url);                                
                        jblV7.setIcon(new ImageIcon(img7));
                        url = this.getClass().getResource(drama[7]);
                        Image img8 = ImageIO.read(url);                                
                        jblV8.setIcon(new ImageIcon(img8));
                    } catch (Exception e) {
                    }
                break;
            case "Terror":
                try {
                        URL url = this.getClass().getResource(terror[0]);
                        Image img1 = ImageIO.read(url);
                        jblV1.setIcon(new ImageIcon(img1));
                        url = this.getClass().getResource(terror[1]);
                        Image img2 = ImageIO.read(url);
                        jblV2.setIcon(new ImageIcon(img2));
                        url = this.getClass().getResource(terror[2]);
                        Image img3 = ImageIO.read(url);
                        jblV3.setIcon(new ImageIcon(img3));
                        url = this.getClass().getResource(terror[3]);
                        Image img4 = ImageIO.read(url);
                        jblV4.setIcon(new ImageIcon(img4));
                        url = this.getClass().getResource(terror[4]);
                        Image img5 = ImageIO.read(url);
                        jblV5.setIcon(new ImageIcon(img5));
                        url = this.getClass().getResource(terror[5]);
                        Image img6 = ImageIO.read(url);                                
                        jblV6.setIcon(new ImageIcon(img6));
                        url = this.getClass().getResource(terror[6]);
                        Image img7 = ImageIO.read(url);                                
                        jblV7.setIcon(new ImageIcon(img7));
                        url = this.getClass().getResource(terror[7]);
                        Image img8 = ImageIO.read(url);                                
                        jblV8.setIcon(new ImageIcon(img8));
                    } catch (Exception e) {
                    }
                break;
            case "Suspenso":
                try {
                        URL url = this.getClass().getResource(suspenso[0]);
                        Image img1 = ImageIO.read(url);
                        jblV1.setIcon(new ImageIcon(img1));
                        url = this.getClass().getResource(suspenso[1]);
                        Image img2 = ImageIO.read(url);
                        jblV2.setIcon(new ImageIcon(img2));
                        url = this.getClass().getResource(suspenso[2]);
                        Image img3 = ImageIO.read(url);
                        jblV3.setIcon(new ImageIcon(img3));
                        url = this.getClass().getResource(suspenso[3]);
                        Image img4 = ImageIO.read(url);
                        jblV4.setIcon(new ImageIcon(img4));
                        url = this.getClass().getResource(suspenso[4]);
                        Image img5 = ImageIO.read(url);
                        jblV5.setIcon(new ImageIcon(img5));
                        url = this.getClass().getResource(suspenso[5]);
                        Image img6 = ImageIO.read(url);                                
                        jblV6.setIcon(new ImageIcon(img6));
                        url = this.getClass().getResource(suspenso[6]);
                        Image img7 = ImageIO.read(url);                                
                        jblV7.setIcon(new ImageIcon(img7));
                        url = this.getClass().getResource(suspenso[7]);
                        Image img8 = ImageIO.read(url);                                
                        jblV8.setIcon(new ImageIcon(img8));
                    } catch (Exception e) {
                    }
                break;
            case "Aventura":
                try {
                        URL url = this.getClass().getResource(aventura[0]);
                        Image img1 = ImageIO.read(url);
                        jblV1.setIcon(new ImageIcon(img1));
                        url = this.getClass().getResource(aventura[1]);
                        Image img2 = ImageIO.read(url);
                        jblV2.setIcon(new ImageIcon(img2));
                        url = this.getClass().getResource(aventura[2]);
                        Image img3 = ImageIO.read(url);
                        jblV3.setIcon(new ImageIcon(img3));
                        url = this.getClass().getResource(aventura[3]);
                        Image img4 = ImageIO.read(url);
                        jblV4.setIcon(new ImageIcon(img4));
                        url = this.getClass().getResource(aventura[4]);
                        Image img5 = ImageIO.read(url);
                        jblV5.setIcon(new ImageIcon(img5));
                        url = this.getClass().getResource(aventura[5]);
                        Image img6 = ImageIO.read(url);                                
                        jblV6.setIcon(new ImageIcon(img6));
                        url = this.getClass().getResource(aventura[6]);
                        Image img7 = ImageIO.read(url);                                
                        jblV7.setIcon(new ImageIcon(img7));
                        url = this.getClass().getResource(aventura[7]);
                        Image img8 = ImageIO.read(url);                                
                        jblV8.setIcon(new ImageIcon(img8));
                    } catch (Exception e) {
                    }
                break;
            case "Ciencia Ficción":
                try {
                        URL url = this.getClass().getResource(ciencia[0]);
                        Image img1 = ImageIO.read(url);
                        jblV1.setIcon(new ImageIcon(img1));
                        url = this.getClass().getResource(ciencia[1]);
                        Image img2 = ImageIO.read(url);
                        jblV2.setIcon(new ImageIcon(img2));
                        url = this.getClass().getResource(ciencia[2]);
                        Image img3 = ImageIO.read(url);
                        jblV3.setIcon(new ImageIcon(img3));
                        url = this.getClass().getResource(ciencia[3]);
                        Image img4 = ImageIO.read(url);
                        jblV4.setIcon(new ImageIcon(img4));
                        url = this.getClass().getResource(ciencia[4]);
                        Image img5 = ImageIO.read(url);
                        jblV5.setIcon(new ImageIcon(img5));
                        url = this.getClass().getResource(ciencia[5]);
                        Image img6 = ImageIO.read(url);                                
                        jblV6.setIcon(new ImageIcon(img6));
                        url = this.getClass().getResource(ciencia[6]);
                        Image img7 = ImageIO.read(url);                                
                        jblV7.setIcon(new ImageIcon(img7));
                        url = this.getClass().getResource(ciencia[7]);
                        Image img8 = ImageIO.read(url);                                
                        jblV8.setIcon(new ImageIcon(img8));
                    } catch (Exception e) {
                    }
                break;
            case "Musical":
                try {
                        URL url = this.getClass().getResource(musical[0]);
                        Image img1 = ImageIO.read(url);
                        jblV1.setIcon(new ImageIcon(img1));
                        url = this.getClass().getResource(musical[1]);
                        Image img2 = ImageIO.read(url);
                        jblV2.setIcon(new ImageIcon(img2));
                        url = this.getClass().getResource(musical[2]);
                        Image img3 = ImageIO.read(url);
                        jblV3.setIcon(new ImageIcon(img3));
                        url = this.getClass().getResource(musical[3]);
                        Image img4 = ImageIO.read(url);
                        jblV4.setIcon(new ImageIcon(img4));
                        url = this.getClass().getResource(musical[4]);
                        Image img5 = ImageIO.read(url);
                        jblV5.setIcon(new ImageIcon(img5));
                        url = this.getClass().getResource(musical[5]);
                        Image img6 = ImageIO.read(url);                                
                        jblV6.setIcon(new ImageIcon(img6));
                        url = this.getClass().getResource(musical[6]);
                        Image img7 = ImageIO.read(url);                                
                        jblV7.setIcon(new ImageIcon(img7));
                        url = this.getClass().getResource(musical[7]);
                        Image img8 = ImageIO.read(url);                                
                        jblV8.setIcon(new ImageIcon(img8));
                    } catch (Exception e) {
                    }
                break;
            case "Infantil":
                try {
                        URL url = this.getClass().getResource(infantil[0]);
                        Image img1 = ImageIO.read(url);
                        jblV1.setIcon(new ImageIcon(img1));
                        url = this.getClass().getResource(infantil[1]);
                        Image img2 = ImageIO.read(url);
                        jblV2.setIcon(new ImageIcon(img2));
                        url = this.getClass().getResource(infantil[2]);
                        Image img3 = ImageIO.read(url);
                        jblV3.setIcon(new ImageIcon(img3));
                        url = this.getClass().getResource(infantil[3]);
                        Image img4 = ImageIO.read(url);
                        jblV4.setIcon(new ImageIcon(img4));
                        url = this.getClass().getResource(infantil[4]);
                        Image img5 = ImageIO.read(url);
                        jblV5.setIcon(new ImageIcon(img5));
                        url = this.getClass().getResource(infantil[5]);
                        Image img6 = ImageIO.read(url);                                
                        jblV6.setIcon(new ImageIcon(img6));
                        url = this.getClass().getResource(infantil[6]);
                        Image img7 = ImageIO.read(url);                                
                        jblV7.setIcon(new ImageIcon(img7));
                        url = this.getClass().getResource(infantil[7]);
                        Image img8 = ImageIO.read(url);                                
                        jblV8.setIcon(new ImageIcon(img8));
                    } catch (Exception e) {
                    }
                break;
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void btnAumentarHotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAumentarHotActionPerformed
        // TODO add your handling code here:
        jblHotDoh.setText(String.valueOf(aumentar()));
    }//GEN-LAST:event_btnAumentarHotActionPerformed

    private void btnAumentarKFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAumentarKFCActionPerformed
        // TODO add your handling code here:
        jblKFC.setText(String.valueOf(aumentar()));
    }//GEN-LAST:event_btnAumentarKFCActionPerformed

    private void btnAumentarBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAumentarBebidaActionPerformed
        // TODO add your handling code here:
        jblBebidas.setText(String.valueOf(aumentar()));
    }//GEN-LAST:event_btnAumentarBebidaActionPerformed

    private void btnAumentarDulceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAumentarDulceActionPerformed
        // TODO add your handling code here:
        jblDulces.setText(String.valueOf(aumentar()));
    }//GEN-LAST:event_btnAumentarDulceActionPerformed

    private void btnAumentarBurguerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAumentarBurguerActionPerformed
        // TODO add your handling code here:
        jblPoliburguer.setText(String.valueOf(aumentar()));
    }//GEN-LAST:event_btnAumentarBurguerActionPerformed

    private void btnAumentarCanguilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAumentarCanguilActionPerformed
        // TODO add your handling code here:        
        jblCanguil.setText(String.valueOf(aumentar()));                
    }//GEN-LAST:event_btnAumentarCanguilActionPerformed

    private void btnDisminuirCanguilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisminuirCanguilActionPerformed
        // TODO add your handling code here:
        jblCanguil.setText(String.valueOf(disminuir()));
    }//GEN-LAST:event_btnDisminuirCanguilActionPerformed

    private void btnAumentarNachosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAumentarNachosActionPerformed
        // TODO add your handling code here:
        jblNachos.setText(String.valueOf(aumentar()));
    }//GEN-LAST:event_btnAumentarNachosActionPerformed

    private void btnDisminuirNachosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisminuirNachosActionPerformed
        // TODO add your handling code here:
        jblNachos.setText(String.valueOf(disminuir()));
    }//GEN-LAST:event_btnDisminuirNachosActionPerformed

    private void btnAumentarPapasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAumentarPapasActionPerformed
        // TODO add your handling code here:
        jblPapas.setText(String.valueOf(aumentar()));
    }//GEN-LAST:event_btnAumentarPapasActionPerformed

    private void btnDisminuirPapasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisminuirPapasActionPerformed
        // TODO add your handling code here:
        jblPapas.setText(String.valueOf(disminuir()));
    }//GEN-LAST:event_btnDisminuirPapasActionPerformed

    private void btnDisminuirHotDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisminuirHotDogActionPerformed
        // TODO add your handling code here:
        jblHotDoh.setText(String.valueOf(disminuir()));
    }//GEN-LAST:event_btnDisminuirHotDogActionPerformed

    private void btnDisminuirKFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisminuirKFCActionPerformed
        // TODO add your handling code here:
        jblKFC.setText(String.valueOf(disminuir()));
    }//GEN-LAST:event_btnDisminuirKFCActionPerformed

    private void btnDisminuirBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisminuirBebidaActionPerformed
        // TODO add your handling code here:
        jblBebidas.setText(String.valueOf(disminuir()));
    }//GEN-LAST:event_btnDisminuirBebidaActionPerformed

    private void btnDisminuirDulcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisminuirDulcesActionPerformed
        // TODO add your handling code here:
        jblDulces.setText(String.valueOf(disminuir()));
    }//GEN-LAST:event_btnDisminuirDulcesActionPerformed

    private void btnDisminuirBurguerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisminuirBurguerActionPerformed
        // TODO add your handling code here:
        jblPoliburguer.setText(String.valueOf(disminuir()));
    }//GEN-LAST:event_btnDisminuirBurguerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PoliSnacks;
    private javax.swing.JButton btnAumentarBebida;
    private javax.swing.JButton btnAumentarBurguer;
    private javax.swing.JButton btnAumentarCanguil;
    private javax.swing.JButton btnAumentarDulce;
    private javax.swing.JButton btnAumentarHot;
    private javax.swing.JButton btnAumentarKFC;
    private javax.swing.JButton btnAumentarNachos;
    private javax.swing.JButton btnAumentarPapas;
    private javax.swing.JButton btnDisminuirBebida;
    private javax.swing.JButton btnDisminuirBurguer;
    private javax.swing.JButton btnDisminuirCanguil;
    private javax.swing.JButton btnDisminuirDulces;
    private javax.swing.JButton btnDisminuirHotDog;
    private javax.swing.JButton btnDisminuirKFC;
    private javax.swing.JButton btnDisminuirNachos;
    private javax.swing.JButton btnDisminuirPapas;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jblBebidas;
    private javax.swing.JLabel jblCanguil;
    private javax.swing.JLabel jblDulces;
    private javax.swing.JPanel jblHotDog;
    private javax.swing.JLabel jblHotDoh;
    private javax.swing.JLabel jblKFC;
    private javax.swing.JLabel jblNachos;
    private javax.swing.JLabel jblPapas;
    private javax.swing.JLabel jblPoliburguer;
    private javax.swing.JLabel jblV1;
    public javax.swing.JLabel jblV2;
    private javax.swing.JLabel jblV3;
    private javax.swing.JLabel jblV4;
    private javax.swing.JLabel jblV5;
    private javax.swing.JLabel jblV6;
    private javax.swing.JLabel jblV7;
    private javax.swing.JLabel jblV8;
    // End of variables declaration//GEN-END:variables
}
